'use client';

import { useState, useCallback } from 'react';
import { AuthGuard } from '@/components/layout/AuthGuard';
import { Navbar } from '@/components/layout/Navbar';
import { SwapCard } from '@/components/swaps/SwapCard';
import { TransitMap } from '@/components/swaps/TransitMap';
import { useAuthStore } from '@/lib/stores/authStore';
import { useSwapStore } from '@/lib/stores/swapStore';
import { useCarbonStore } from '@/lib/stores/carbonStore';
import { SwapSuggestion } from '@/types/gemini';
import { RefreshCw, Sparkles, MapPin, ChevronRight } from 'lucide-react';

function SwapsContent() {
  const { profile } = useAuthStore();
  const { weeklyData } = useCarbonStore();
  const { swaps, isLoading, setSwaps, setLoading } = useSwapStore();
  const [error, setError] = useState('');
  const [hasFetched, setHasFetched] = useState(false);

  const weeklyAvgCo2 = weeklyData.reduce((s, v) => s + v, 0) / 7;

  const fetchSwaps = useCallback(async () => {
    if (!profile) return;
    setLoading(true);
    setError('');
    try {
      const res = await fetch('/api/gemini', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          endpoint: 'swaps',
          payload: {
            archetype: profile.archetype ?? 'lifestyle',
            topCategory: profile.topCategory ?? 'transport',
            weeklyAvgCo2,
          },
        }),
      });
      const data = await res.json();
      setSwaps(data.data.swaps as SwapSuggestion[]);
      setHasFetched(true);
    } catch (err) {
      setError('Could not load swaps. Please check your connection.');
    } finally {
      setLoading(false);
    }
  }, [profile, weeklyAvgCo2]);

  return (
    <div className="app-layout">
      <Navbar />

      <main className="main-content">
        <div className="max-w-2xl mx-auto w-full">
          {/* Breadcrumbs */}
          <div className="flex items-center gap-1 text-[11px] text-[#5f6368] font-medium mb-3 animate-fade-in">
            <span>EcoPulse</span>
            <ChevronRight size={10} className="mt-0.5" />
            <span className="text-[#202124]">Swaps</span>
          </div>

          {/* Header */}
          <div className="flex items-start justify-between mb-6 animate-fade-in">
            <div>
              <p className="text-subheading">AI Recommendations</p>
              <h1 className="font-bold text-[#202124]" style={{ fontSize: '1.5rem', marginTop: '0.25rem' }}>
                Your Swaps
              </h1>
              <p className="text-xs mt-1" style={{ color: '#5f6368' }}>
                Personalized suggestions generated by Gemini AI to optimize your carbon footprint
              </p>
            </div>
            <button
              onClick={fetchSwaps}
              disabled={isLoading}
              className="btn-ghost flex items-center gap-2 cursor-pointer"
              style={{ flexShrink: 0, padding: '0.4rem 0.85rem', fontSize: '0.78rem' }}
            >
              <RefreshCw size={13} className={isLoading ? 'animate-spin' : ''} />
              {isLoading ? 'Loading…' : swaps.length > 0 ? 'Refresh' : 'Generate'}
            </button>
          </div>

          <div className="flex flex-col gap-6">
            {/* AI swaps section */}
            <div>
              <div className="flex items-center gap-2 mb-3.5">
                <Sparkles size={14} style={{ color: '#1a73e8' }} />
                <h2 className="text-heading" style={{ fontSize: '0.9rem', color: '#202124', fontWeight: 650 }}>
                  Active Recommendations
                </h2>
              </div>

              {!hasFetched && swaps.length === 0 && !isLoading && (
                <div
                  className="flex flex-col items-center justify-center py-10 rounded bg-white border border-[#dadce0] text-center animate-fade-in shadow-sm"
                >
                  <div className="text-3xl mb-2">✨</div>
                  <p className="font-semibold text-xs mb-1" style={{ color: '#202124' }}>
                    Ready to generate your recommendations
                  </p>
                  <p className="text-xs mb-4 max-w-sm px-4" style={{ color: '#5f6368', lineHeight: 1.5 }}>
                    Gemini AI will analyze your {profile?.archetype ? `"${profile.archetype}"` : ''} profile details and construct target reductions
                  </p>
                  <button onClick={fetchSwaps} className="btn-primary cursor-pointer" style={{ padding: '0.5rem 1rem', fontSize: '0.8rem' }}>
                    <Sparkles size={13} />
                    Generate Swaps
                  </button>
                </div>
              )}

              {isLoading && (
                <div className="flex flex-col items-center justify-center py-12 gap-3 bg-white border border-[#dadce0] rounded shadow-sm">
                  <div
                    className="w-8 h-8 rounded-full border-2 animate-spin"
                    style={{ borderColor: '#dadce0', borderTopColor: '#1a73e8' }}
                  />
                  <p className="font-semibold text-xs" style={{ color: '#5f6368' }}>
                    Gemini is crafting active recommendations…
                  </p>
                </div>
              )}

              {error && (
                <div
                  className="px-4 py-3 rounded text-xs border font-semibold"
                  style={{ background: '#fce8e6', borderColor: '#fad2cf', color: '#c5221f' }}
                >
                  {error}
                </div>
              )}

              {!isLoading && swaps.length > 0 && (
                <div className="flex flex-col gap-4">
                  {swaps.map((swap, i) => (
                    <SwapCard key={i} swap={swap} index={i} />
                  ))}
                </div>
              )}
            </div>

            {/* Commute Comparisons */}
            <div>
              <div className="flex items-center gap-2 mb-3.5">
                <MapPin size={14} style={{ color: '#137333' }} />
                <h2 className="text-heading" style={{ fontSize: '0.9rem', color: '#202124', fontWeight: 650 }}>
                  Commute Route Comparisons
                </h2>
              </div>
              <div className="flex flex-col gap-4">
                <TransitMap routeId="commute-main" />
                <TransitMap routeId="grocery-run" />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default function SwapsPage() {
  return (
    <AuthGuard>
      <SwapsContent />
    </AuthGuard>
  );
}
